### ISSUE TITLE
The gulp file seems to be invalid

### ISSUE THREAD

**Issue by Fastjur** [FrontEndCoffee/platform-game#6]
![image](https://cloud.githubusercontent.com/assets/1493561/15451440/c39d76ea-1fc2-11e6-9f42-2438054f81ca.png)

**Comment by FrontEndCoffee** [comment]
This seems to be a warning from your JSLinter. Maybe it has to do with the fact that I used arrow functions (an ECMA6 feature). BTW i see that you used semicolons. Please don't use them in this project, it will get confusing if we both write in different styles. And if you do it because your IDE is nagging about it, please reconfigure the built in linter.
